CREATE TABLE ACCESS_HISTORY ( 
	ID							INT AUTO_INCREMENT PRIMARY KEY, 
	USERID						INT,
	IP							VARCHAR(16),
	BROWSER						VARCHAR(100),
	OPERATING_SYSTEM			VARCHAR(100),
	ACCESS_DATE					DATE DEFAULT NOW()
);

CREATE TABLE LOGIN (
	ID			INT PRIMARY KEY,
	LOGIN_DATE	DATE,
	AGE_RANGE	INT
);